# Generated by Django 5.2.7 on 2025-10-22 12:44

import activacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=activacion.models.ruta_activacion)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_activacion', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento de Activación',
                'verbose_name_plural': 'Documentos de Activación',
                'ordering': ['cliente__nombre', 'tipo_documento'],
            },
        ),
    ]
