# Generated by Django 5.2.6 on 2025-09-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('factura', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_honorarios', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estatus_periodo', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
