# Generated by Django 5.2.6 on 2025-09-30 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersion',
            name='comision_procom',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispersion',
            name='factura_honorarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='comision',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='factura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='total_honorarios',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
