# Generated by Django 5.2.6 on 2025-10-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0002_dispersion_comision_procom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispersion',
            name='pagado_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
