# Generated by Django 5.2.6 on 2025-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0003_dispersion_pagado_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='pagado_checkbox',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
