# Generated by Django 5.2.6 on 2025-10-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0004_alter_dispersion_pagado_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispersion',
            old_name='pagado_checkbox',
            new_name='estatus_pago',
        ),
    ]
