# Generated by Django 5.2.7 on 2025-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0005_rename_pagado_checkbox_dispersion_estatus_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispersion',
            old_name='factura_honorarios',
            new_name='num_factura',
        ),
        migrations.AddField(
            model_name='dispersion',
            name='num_factura_honorarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
