# Generated by Django 5.2.7 on 2025-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0006_rename_factura_honorarios_dispersion_num_factura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispersion',
            options={'permissions': [('actualizar_estatus_dispersion', 'Puede actualizar estatus de pago en dispersiones')]},
        ),
    ]
