# Generated by Django 5.2.7 on 2025-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0007_alter_dispersion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispersion',
            old_name='estatus',
            new_name='num_periodo',
        ),
        migrations.AddField(
            model_name='dispersion',
            name='proceso',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
