# Generated by Django 5.2.7 on 2025-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0008_rename_estatus_dispersion_num_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='proceso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
