# Generated by Django 5.2.7 on 2025-10-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0009_alter_dispersion_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispersion',
            name='num_periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispersion',
            name='proceso',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
