# Generated by Django 5.2.7 on 2025-10-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0010_alter_dispersion_num_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispersion',
            name='num_periodo',
        ),
    ]
