# Generated by Django 5.2.7 on 2025-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0011_remove_dispersion_num_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispersion',
            old_name='proceso',
            new_name='estatus_proceso',
        ),
        migrations.AddField(
            model_name='dispersion',
            name='num_periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
