# Generated by Django 5.2.7 on 2025-10-20 11:11

import django.db.models.deletion
import materialidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMaterialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('identificacion', 'Identificación'), ('rfc', 'RFC'), ('contrato', 'Contrato'), ('acta_constitutiva', 'Acta Constitutiva'), ('comprobante_domicilio', 'Comprobante de Domicilio')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=materialidad.models.ruta_materialidad)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_materialidad', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento de Materialidad',
                'verbose_name_plural': 'Documentos de Materialidad',
                'ordering': ['cliente__nombre', 'tipo_documento'],
            },
        ),
    ]
