# Generated by Django 5.2.7 on 2025-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomaterialidad',
            name='tipo_documento',
            field=models.CharField(max_length=50),
        ),
    ]
