# Generated by Django 5.2.6 on 2025-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('utilidad_enrok', models.FloatField(blank=True, null=True)),
                ('comisionista_1', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_1', models.FloatField(blank=True, null=True)),
                ('comisionista_2', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_2', models.FloatField(blank=True, null=True)),
                ('comisionista_3', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_3', models.FloatField(blank=True, null=True)),
                ('comisionista_4', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_4', models.FloatField(blank=True, null=True)),
                ('comisionista_5', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_5', models.FloatField(blank=True, null=True)),
                ('comisionista_6', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_6', models.FloatField(blank=True, null=True)),
                ('comisionista_7', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_7', models.FloatField(blank=True, null=True)),
                ('comisionista_8', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_8', models.FloatField(blank=True, null=True)),
                ('comisionista_9', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_9', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
