# Generated by Django 5.2.6 on 2025-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comision_procom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
