# Generated by Django 5.2.7 on 2025-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='factura',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
