# Generated by Django 5.2.7 on 2025-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='factura',
            field=models.CharField(blank=True, null=True),
        ),
    ]
