# Generated by Django 5.2.7 on 2025-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(default='Persona moral', max_length=50),
            preserve_default=False,
        ),
    ]
