# Generated by Django 5.2.6 on 2025-09-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_id'),
        ('dispersiones', '0002_dispersion_comision_procom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionista', models.CharField(max_length=255)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('dispersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='dispersiones.dispersion')),
            ],
        ),
    ]
