# Generated by Django 5.2.6 on 2025-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='estatus',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
