# Generated by Django 5.2.6 on 2025-10-01 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_comision_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComisionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionista', models.CharField(max_length=255)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_pago', '-creado'],
            },
        ),
        migrations.AlterField(
            model_name='comision',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
