# Generated by Django 5.2.6 on 2025-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0003_pagocomisionista_alter_comision_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionista', models.CharField(max_length=255)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PagoComisionista',
        ),
    ]
