# Generated by Django 5.2.7 on 2025-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0004_pago_delete_pagocomisionista'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='anio_real',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mes_real',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
